learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logs/', include('logs.urls')),
]

logs/urls.py
from django.urls import path
from logs import views

app_name = "logs"

urlpatterns = [
    path('', views.index),
    path('topics/', views.topics,name="topics"),
    path('new_topic/', views.new_topic, name="new_topic"),
]

logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):                      #id is made automatically
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE) # show that it needs sth on delete
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'    #django pluralises so we put this to get entries instead of entrys

    def __str__(self):
        return f"{self.text[:50]}..."   #display a clipped version

logs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields =['text']
        labels = {'text' : 'type the topic here'}

logs/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from logs.models import Topic, Entry
from .forms import TopicForm
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here. request is a python object rendering http request
def index(request):
    return render(request,"base.html")
    #return HttpResponse("<h1>hello django!<\h1>")

def topics(request):
    context = {}
    t = Topic.objects.all()
    context["topics"] = t
    return render(request, "topics.html",context)

def new_topic(request):
    '''add a new topic'''
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('logs:topics'))

    return render(request, 'new_topic.html',context={"form":form})

logs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Logs</title>
</head>
<body>
    <h1>Hello Bob</h1>

    {% block content %}

    {% endblock %}



    {% block footer %}
    <p>mumumu</p>
    {% endblock %}

</body>
</html>

logs/templates/index.html
{% extends "base.html" %}

    {% block content %}
        <h2>whatsupppp</h2>
    {% endblock content %}

    {% block footer %}
        <ol>
            <li>wfpeij</li>
            <li>wrohkwrh</li>
            <li>setdtk</li>
        </ol>
    {% endblock footer%}

logs/templates/new_topic.html
{% extends "base.html" %}

    {% block content %}

        <p>Add a new topic:</p>
        <form action="{% url 'logs:new_topic' %}" method='post'>
            {% csrf_token %}

            {{form}}
            <button name="submit">add topic</button>
        </form>

    {% endblock %}

logs/templates/topics.html
{% extends "base.html" %}

{% block content %}
    <ol>
        {% for topic in topics %}
        <li>{{topic}}</li>
        {% endfor %}
    </ol>

    <button><a href="{% url 'logs:new_topic' %}">add a topic here</a></button>

{% endblock content %}